### PR TITLE
Main Launch VC Finished

### LINKED ISSUE #6: User Profile Creation
As a user I'd like to be able to make a profile on the PlayDate app.

- [ ] User Model
- [ ] Registration
- [ ] Login
- [ ] User Profile Setup

### PR DESCRIPTION
**Pull request by dabaquita**
Please let me know if we should be adding any more things or if anything is off. 

Here is the picture of the final view:

simulator_screenshot_6BD576EE-AA09-4F69-B2E3-43D5029ABF1B

### CODE REVIEW

**Comment by dabaquita** [comment]
Testing a webhook. Also reminder to review this please

**Comment by dabaquita** [comment]
Testing the webhook

**Review by michaelsoffline — APPROVED** [review]
Looks fine to me, but (and it could just be my eyes) it looks like the logo may be wider and shorter than it appears in the Figma. I don't know how exact we want it to match the Figma layouts though, so I'll leave it up to you.

**Comment by dabaquita** [comment]
> Looks fine to me, but (and it could just be my eyes) it looks like the logo may be wider and shorter than it appears in the Figma. I don't know how exact we want it to match the Figma layouts though, so I'll leave it up to you.


Good catch! I'll send an update to this one soon.

**Comment by dabaquita** [comment]
Added the changes and fixed the constraints as seen below: 

simulator_screenshot_941AED6D-E886-4543-82A9-CCB40F730377

**Pull request merged**
